services:
  - type: web
    name: pos-backend
    runtime: node
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm run db:seeder && npm start

  - type: web
    name: pos-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://api.lovkimtech.store